import { Inter } from "next/font/google";

import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Calculation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "flex w-screen min-w-fit justify-center px-8 pt-10 sm:px-0",
        )}
      >
        {children}
      </body>
    </html>
  );
}
